### ISSUE TITLE
Missing 'utils'

### ISSUE THREAD

**Issue by ErikMelton** [Oleffa/LeagueAI#5]
It appears that a library that you wrote called 'utils' is not included in the GitHub repo, and I cannot build the LegueAI.py file

**Comment by Oleffa** [comment]
Hi and sorry for the late answer.

This looks like an error caused by the Tensorflow object detection API setup. The utils should be included in the object detection api repository: Similar to https://github.com/tensorflow/models/tree/master/research/object_detection/utils.

Did you set up the Tensorflow object detection API correctly? (clone the repo, copy LeagueAI.py and the trained network as a folder LeagueAI_v3 in the object_detection folder) Also, did you set your python path and run the protoc command as shown in https://pythonprogramming.net/introduction-use-tensorflow-object-detection-api-tutorial/ ?

If you can post the exact error you get I can see if there is another problem.

Best Regards
